### ISSUE TITLE
There is no method called accept() in this class.

### ISSUE THREAD

**Issue by sbimochan** [ikushum/Django-Vue-Chat-App#1]
https://github.com/ikushum/Django-Vue-Chat-App/blob/ffdf4e5cdd25e9b7a3b6c6c46bacdca3d01f2a12/chat/consumers.py#L19

**Comment by ikushum** [comment]
The ```accept()``` method is inherited from ```WebsocketConsumer```

For a more detailed explanation, please take a look at the [documentation](https://channels.readthedocs.io/en/latest/topics/consumers.html#websocketconsumer)
