### ISSUE TITLE
Deploying on AWS server with nginx and gunicorn

### ISSUE THREAD

**Issue by mat0ccdeekk** [ikushum/Django-Vue-Chat-App#5]
I have a django project, on AWS server with nginx, gunicorn and HTTPS protocol . How to deploying the chat app ?
Thank you

**Comment by ikushum** [comment]
@mat0ccdeekk 

Thanks for raising the issue

Here are a few articles that should help you

1. https://channels.readthedocs.io/en/latest/deploying.html
2. https://avilpage.com/2018/05/deploying-scaling-django-channels.html
3. https://medium.com/@elspanishgeek/how-to-deploy-django-channels-2-x-on-aws-elastic-beanstalk-8621771d4ff0

The first one is from the official documentation of Django channels

I hope that helps

**Comment by mat0ccdeekk** [comment]
ok thank you
